import { useState } from 'react'
import { X, Upload, Check, AlertCircle, FileText, UserPlus, Users, Save } from 'lucide-react'
import { collection, addDoc, updateDoc, doc } from 'firebase/firestore'
import { db } from '../firebase'
import { parseRateSheetPDF } from '../lib/rateSheetParser'
import { syncServiceRatesToRateCard } from '../lib/serviceRatesSync'

export default function RateCardUploader({ clients, onClose, onSaved }) {
  const [file, setFile] = useState(null)
  const [parsing, setParsing] = useState(false)
  const [result, setResult] = useState(null)  // { rates, found, missing, unknown }
  const [error, setError] = useState(null)

  const [mode, setMode] = useState('existing')  // 'existing' | 'new'
  const [selectedClientId, setSelectedClientId] = useState('')
  const [newClientName, setNewClientName] = useState('')
  const [newClientContact, setNewClientContact] = useState('')
  const [newClientEmail, setNewClientEmail] = useState('')
  const [saving, setSaving] = useState(false)

  const handleFile = async (f) => {
    if (!f) return
    setFile(f); setError(null); setResult(null); setParsing(true)
    try {
      const r = await parseRateSheetPDF(f)
      setResult(r)
      if (r.found.length === 0) {
        setError('No rate fields found in this PDF. Make sure it was generated by JCT (purple "Generate Rate Card" button).')
      }
    } catch (e) {
      console.error(e)
      setError('Failed to read PDF: ' + e.message)
    } finally {
      setParsing(false)
    }
  }

  const onDrop = (e) => {
    e.preventDefault()
    const f = e.dataTransfer.files[0]
    if (f && f.type === 'application/pdf') handleFile(f)
    else setError('Please drop a PDF file.')
  }

  const save = async () => {
    if (!result || result.found.length === 0) return
    setSaving(true); setError(null)
    try {
      const serviceRates = {
        ...result.rates,
        uploadedAt: new Date().toISOString(),
        uploadedFrom: file?.name || 'signed PDF',
      }

      if (mode === 'existing') {
        if (!selectedClientId) { setError('Pick a client first.'); setSaving(false); return }
        await updateDoc(doc(db, 'clients', selectedClientId), { serviceRates, rateCard: syncServiceRatesToRateCard(serviceRates) })
        onSaved?.({ clientId: selectedClientId, mode: 'existing' })
      } else {
        if (!newClientName.trim()) { setError('Enter a company name.'); setSaving(false); return }
        const ref = await addDoc(collection(db, 'clients'), {
          companyName: newClientName.trim(),
          contactName: newClientContact.trim(),
          email: newClientEmail.trim(),
          createdAt: new Date().toISOString(),
          startDate: new Date().toISOString().slice(0, 10),
          serviceRates,
          rateCard: syncServiceRatesToRateCard(serviceRates),
        })
        onSaved?.({ clientId: ref.id, mode: 'new' })
      }
      onClose()
    } catch (e) {
      console.error(e)
      setError('Save failed: ' + e.message)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4" onClick={onClose}>
      <div className="bg-gray-900 border border-gray-700 rounded-xl max-w-3xl w-full max-h-[92vh] overflow-hidden flex flex-col"
           onClick={(e) => e.stopPropagation()}>

        {/* Header */}
        <div className="px-5 py-3 border-b border-gray-800 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Upload size={16} className="text-green-400" />
            <div>
              <h3 className="text-base font-semibold text-white">Upload Signed Rate Card</h3>
              <p className="text-xs text-gray-400">Parse a filled JCT rate sheet and apply to a client</p>
            </div>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-white"><X size={18} /></button>
        </div>

        {/* File drop zone */}
        <div className="p-5 space-y-3">
          {!file && (
            <div onDrop={onDrop} onDragOver={(e) => e.preventDefault()}
              className="border-2 border-dashed border-gray-700 rounded-lg p-8 text-center hover:border-blue-500 transition-colors">
              <FileText size={32} className="mx-auto text-gray-500 mb-2" />
              <p className="text-sm text-gray-300 mb-1">Drop your signed PDF here</p>
              <p className="text-xs text-gray-500 mb-3">or</p>
              <label className="bg-blue-600 hover:bg-blue-500 text-white text-sm px-4 py-1.5 rounded-lg cursor-pointer inline-block">
                Choose File
                <input type="file" accept="application/pdf" className="hidden"
                  onChange={(e) => handleFile(e.target.files[0])} />
              </label>
            </div>
          )}

          {file && (
            <div className="bg-gray-800/50 border border-gray-700 rounded-lg p-3 flex items-center justify-between">
              <div className="flex items-center gap-2 min-w-0">
                <FileText size={14} className="text-blue-400 flex-shrink-0" />
                <span className="text-sm text-white truncate">{file.name}</span>
                <span className="text-xs text-gray-500">({(file.size / 1024).toFixed(1)} KB)</span>
              </div>
              <button onClick={() => { setFile(null); setResult(null); setError(null) }}
                className="text-xs text-gray-400 hover:text-red-400">Replace</button>
            </div>
          )}

          {parsing && <p className="text-sm text-blue-400 text-center">Parsing PDF…</p>}

          {error && (
            <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3 flex items-start gap-2">
              <AlertCircle size={14} className="text-red-400 flex-shrink-0 mt-0.5" />
              <p className="text-xs text-red-300">{error}</p>
            </div>
          )}

          {result && result.found.length > 0 && (
            <div className="bg-green-500/10 border border-green-500/30 rounded-lg p-3 space-y-2">
              <div className="flex items-center gap-2">
                <Check size={14} className="text-green-400" />
                <p className="text-sm text-green-300 font-semibold">
                  Extracted {result.found.length} rates
                  {result.missing.length > 0 && ` (${result.missing.length} blank)`}
                </p>
              </div>
              <div className="max-h-40 overflow-y-auto text-xs">
                <div className="grid grid-cols-2 gap-x-4 gap-y-0.5">
                  {result.found.map(k => (
                    <div key={k} className="flex justify-between gap-2">
                      <span className="text-gray-400 truncate">{k}</span>
                      <span className="text-green-300 font-mono">${result.rates[k]?.toFixed(2)}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Apply to client */}
        {result && result.found.length > 0 && (
          <div className="px-5 pb-5 space-y-3 border-t border-gray-800 pt-4">
            <h4 className="text-sm font-semibold text-white">Apply rates to:</h4>
            <div className="grid grid-cols-2 gap-2">
              <button onClick={() => setMode('existing')}
                className={`flex items-center gap-2 p-3 rounded-lg border ${
                  mode === 'existing' ? 'bg-blue-600 border-blue-500 text-white' : 'bg-gray-800 border-gray-700 text-gray-300 hover:border-gray-600'
                }`}>
                <Users size={14} />
                <div className="text-left">
                  <div className="text-sm font-semibold">Existing client</div>
                  <div className="text-[11px] opacity-80">Update rates for current client</div>
                </div>
              </button>
              <button onClick={() => setMode('new')}
                className={`flex items-center gap-2 p-3 rounded-lg border ${
                  mode === 'new' ? 'bg-blue-600 border-blue-500 text-white' : 'bg-gray-800 border-gray-700 text-gray-300 hover:border-gray-600'
                }`}>
                <UserPlus size={14} />
                <div className="text-left">
                  <div className="text-sm font-semibold">Onboard new client</div>
                  <div className="text-[11px] opacity-80">Create client with these rates</div>
                </div>
              </button>
            </div>

            {mode === 'existing' && (
              <select value={selectedClientId} onChange={(e) => setSelectedClientId(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 text-white text-sm px-3 py-2 rounded-lg">
                <option value="">— Select client —</option>
                {(clients || []).map(c => (
                  <option key={c.id} value={c.id}>{c.companyName}</option>
                ))}
              </select>
            )}

            {mode === 'new' && (
              <div className="grid grid-cols-1 md:grid-cols-3 gap-2">
                <input value={newClientName} onChange={(e) => setNewClientName(e.target.value)}
                  placeholder="Company name *"
                  className="bg-gray-800 border border-gray-700 text-white text-sm px-3 py-2 rounded-lg" />
                <input value={newClientContact} onChange={(e) => setNewClientContact(e.target.value)}
                  placeholder="Contact name"
                  className="bg-gray-800 border border-gray-700 text-white text-sm px-3 py-2 rounded-lg" />
                <input value={newClientEmail} onChange={(e) => setNewClientEmail(e.target.value)}
                  placeholder="Email"
                  className="bg-gray-800 border border-gray-700 text-white text-sm px-3 py-2 rounded-lg" />
              </div>
            )}
          </div>
        )}

        {/* Footer */}
        <div className="px-5 py-3 border-t border-gray-800 flex justify-end gap-2">
          <button onClick={onClose} className="text-sm text-gray-300 hover:text-white px-3 py-1.5">Cancel</button>
          <button onClick={save}
            disabled={!result || result.found.length === 0 || saving ||
              (mode === 'existing' && !selectedClientId) ||
              (mode === 'new' && !newClientName.trim())}
            className="bg-green-600 hover:bg-green-500 disabled:bg-gray-700 disabled:text-gray-500 text-white text-sm px-3 py-1.5 rounded-lg flex items-center gap-1.5">
            <Save size={14} /> {saving ? 'Saving…' : mode === 'new' ? 'Create Client' : 'Apply Rates'}
          </button>
        </div>
      </div>
    </div>
  )
}
